---
name: "Bingers"
guid: "ac5439e6-35f8-4c3c-b2ef-b69950d1c991"
version: 1
targetAbi: "12.1.0.0"
framework: "net10.0"
owner: "jellyfin"
overview: "Record your watched media with Bingers"
description: >
  Mark the movies and episodes you watch in Jellyfin as watched on bingers.app.

category: "General"
artifacts:
  - "Bingers.dll"
changelog: |-
  - Initial Bingers release, adapted from the Trakt plugin
